### ISSUE TITLE
about PSD extract feature

### ISSUE THREAD

**Issue by daysofchasingdream** [neerajwagh/eeg-gcnn#13]
Hello author, thank you again for your sharing, it has benefited me a lot. I have a question to discuss with you, why did you only consider using PSD to extract features, but did you consider using time-frequency features, which are theoretically more appropriate for epileptic signals? Best wishes~

**Comment by neerajwagh** [comment]
Hi - thanks for your interest in the work!

Band powers (PSD) or power in oscillatory rhythms (extracted after FOOOF modeling) is the traditional baseline for resting state EEG because they have widely accepted physiological/clinical interpretations. You can always extend the list of baseline features to include complex signal-processing-based features, but they may not be accepted/understood/interpreted meaningfully by a clinical audience.

About time-frequency features specifically: In resting-state, once you've created fixed-length 10-second epochs, the time-domain signal within the 10s epoch is typically not of interest since the epoch boundaries are arbitrary. Therefore, time-frequency features make more sense if you have evoked/stimulus-based EEG.

Do let me know if I've misunderstood something or if you think differently. 

Thanks.
