### ISSUE TITLE
Weighted adjacency matrix not used?

### ISSUE THREAD

**Issue by ajrcampbell** [neerajwagh/eeg-gcnn#2]
In your [paper](https://arxiv.org/pdf/2011.12107.pdf), the adjacency matrix is stated to be a weighed combination of structural and functional connectivity `A_ij = 0.5 * (A_ij^s + A_ij^f)`. However, in your [code](https://github.com/neerajwagh/eeg-gcnn/blob/2a5054886373b03b3497b21ca23451da241dc643/code_psd_shallow_eeg-gcnn/EEGGraphDataset.py#L118) the adjacency matrix is binary. Are the presented results from a binary or weighted adjacency matrix?

**Comment by neerajwagh** [comment]
Hey @ajrcampbell, thanks for pointing this out! It's indeed an error in implementation, the matrix is designed to be weighted.

In an effort to preserve the floating-point numpy data during tensor conversion, I seem to have mistakenly chosen long instead of double. I suspect the elements at L117 never exactly equal 2.0. Therefore, they would truncate to either 0 or 1, depending on how strong the total connectivity value is after the summation at L117.

I apologize for the confusion, I'll investigate this further and correct the text accordingly. Thanks again!

**Comment by neerajwagh** [comment]
The results do not change significantly after fixing this bug. Apologies for the delay.

**Comment by neerajwagh** [comment]
@ajrcampbell Let me know if there are any other issues. The latest branch merge fixes the type-casting bug.
